In [0]:
import numpy as np

In [11]:
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
print("matrix_A : ")
print(matrix_A)

matrix_A : 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [14]:
# Matrix + One value : add the value to each element of the matrix
result1 = matrix_A + 5
print("result1 : ")
print(result1)

result1 : 
[[ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]


In [15]:
# 'numpy.random.randn(d0, d1, ..., dn)' makes ndarray. and each element of the ndarray follow standard normal distribution(표준정규분포)
# (d0, d1, ..., dn) is shape of the ndarray
matrix_B = np.random.randn(3, 3)
print("matrix_B : ")
print(matrix_B)
print()

# Matrix + Matrix
result2 = matrix_A + matrix_B
print("result2 : ")
print(result2)

matrix_B : 
[[-0.64100847  2.94880191  1.84569663]
 [ 0.54060114 -0.66345658 -1.10404957]
 [ 0.55060757  0.36238298 -0.69818587]]

result2 : 
[[0.35899153 4.94880191 4.84569663]
 [4.54060114 4.33654342 4.89595043]
 [7.55060757 8.36238298 8.30181413]]


In [17]:
# Matrix * One value : multiply the value and each element of matrix
result3 = matrix_A * 3
print("result3 : ")
print(result3)

result3 : 
[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]


In [20]:
# Matrix * Matrix
result4 = np.matmul(matrix_A, matrix_B)   # using 'numpy.matmul' for matrix multiplication
print("result4 : ")
print(result4)

result4 : 
[[ 2.09201652  2.70903767 -2.45696013]
 [ 3.44261725 10.65222258 -2.32657656]
 [ 4.79321798 18.59540749 -2.196193  ]]


In [21]:
# 'reshape' method gives a new shape to ndarray
matrix_C = np.arange(15).reshape(3, 5)   # shape : (1, 15) -> (3, 5)
matrix_D = np.random.randn(5, 3)

result5 = np.matmul(matrix_C, matrix_D)
print("result5 : ")
print(result5)

result5 : 
[[ -5.22966137  -2.67553744   1.0570648 ]
 [-19.18662793  -4.08942547   0.79078591]
 [-33.14359449  -5.50331349   0.52450702]]


In [22]:
# '*' operation is element-wise multiplication
print("matrix_A : ")
print(matrix_A)
print()

print("matrix_B : ")
print(matrix_B)
print()

result6 = matrix_A * matrix_B
print("result6 : ")
print(result6)

matrix_A : 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

matrix_B : 
[[-0.64100847  2.94880191  1.84569663]
 [ 0.54060114 -0.66345658 -1.10404957]
 [ 0.55060757  0.36238298 -0.69818587]]

result6 : 
[[-0.64100847  5.89760382  5.53708989]
 [ 2.16240456 -3.3172829  -6.62429743]
 [ 3.854253    2.8990638  -6.28367284]]
